### ISSUE TITLE
setup.py doesn't install pulse directory.

### ISSUE THREAD

**Issue by h6w** [Valodim/pamixer#5]
Traceback (most recent call last):
  File "/usr/local/bin/pamixer", line 5, in <module>
    pkg_resources.run_script('pamixer==0.1.4', 'pamixer')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 499, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1235, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/pamixer-0.1.4-py2.7.egg/EGG-INFO/scripts/pamixer", line 13, in <module>
    from pamixer.pulse.ParCur import par
ImportError: No module named pulse.ParCur

However, if I sudo cp -R ~/pamixer/pamixer/pulse /usr/local/lib/python2.7/dist-packages/pamixer-0.1.4-py2.7.egg/pamixer/
then it works ok!

**Comment by hartwork** [comment]
Confirming. Demo from the Git repository:

```
# find pamixer -type d
pamixer
pamixer/pulse
pamixer/screens
pamixer/classes

# python setup.py install --root "${PWD}"/DESTDIR --prefix /usr
[..]

# find DESTDIR/usr/lib64/python2.7/site-packages/pamixer -type d
DESTDIR/usr/lib64/python2.7/site-packages/pamixer
DESTDIR/usr/lib64/python2.7/site-packages/pamixer/screens
DESTDIR/usr/lib64/python2.7/site-packages/pamixer/classes
```

**Comment by hartwork** [comment]
Please `git am` this patch: https://cgit.gentoo.org/proj/betagarden.git/tree/media-sound/pamixer/files/pamixer-0.1.4_pre20120212-install-pamixer-pulse-module.patch
