### ISSUE TITLE
Ncurses problem when printing a long list of clients

### ISSUE THREAD

**Issue by thetrompf** [Valodim/pamixer#6]
Everything works fine for me in pamixer, after fixed the install problems described in issue #5 except the `Client` section of the program, when try to open clients, the program exists with this error:

```
Traceback (most recent call last):
    File "/usr/local/bin/pamixer", line 5, in <module>
        pkg_resources.run_script('pamixer==0.1.4', 'pamixer')
    File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 499, in run_script
        self.require(requires)[0].run_script(script_name, ns)
    File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1235, in run_script
        execfile(script_filename, namespace, namespace)
    File "/usr/local/lib/python2.7/dist-packages/pamixer-0.1.4-py2.7.egg/EGG-INFO/scripts/pamixer", line 32, in <module>
        cur.run()
    File "/usr/local/lib/python2.7/dist-packages/pamixer-0.1.4-py2.7.egg/pamixer/Curses.py", line 156, in run
        curses.wrapper(self.run2)
    File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
        return func(stdscr, *args, **kwds)
    File "/usr/local/lib/python2.7/dist-packages/pamixer-0.1.4-py2.7.egg/pamixer/Curses.py", line 199, in run2
        self.update()
    File "/usr/local/lib/python2.7/dist-packages/pamixer-0.1.4-py2.7.egg/pamixer/Curses.py", line 55, in update
        self.modes[self.active_mode].layout(self.subpad)
    File "/usr/local/lib/python2.7/dist-packages/pamixer-0.1.4-py2.7.egg/pamixer/screens/ScreenClients.py", line 56, in layout
        self.redraw()
    File "/usr/local/lib/python2.7/dist-packages/pamixer-0.1.4-py2.7.egg/pamixer/screens/ScreenClients.py", line 83, in redraw
        wclientlist.addstr(self.clientchars[i] + ": ")
_curses.error: addstr() returned ERR
```

This happens because I have so many clients on my system, so when the program tries to list them all, some of them are listed "outside" the window, which is not allow.

**Comment by hartwork** [comment]
Confirming. By resizing the terminal to a small rectangle, I can force pamixer to crash.
